### ISSUE TITLE
Correct hooktest line in the README example for .travis.yml

### ISSUE THREAD

**Issue by nevenjovanovic** [Capitains/HookTest#103]
The hooktest script line in the example `.travis.yml` script (in the README) has one `./` too many. Currently the line reads:

```
script:  hooktest ./ --console table --scheme epidoc --workers 3 --verbose 5 --manifest --countword --allowfailure ./
```
When I tried to build with Travis using this, the hooktest refused to run. When I removed the first `/.`, like this:

```
script:  hooktest --console table --scheme epidoc --workers 3 --verbose 5 --manifest --countword --allowfailure ./
```
... everything worked as it should

**Comment by sonofmun** [comment]
Fixed in PR #106
