### ISSUE TITLE
@xml:lang not read from <text>

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [Capitains/HookTest#111]
Testing a corpus with Hooktest, I got the error `Correct xml:lang attribute ` when using @xml:base on <text>:

    <text xml:lang="xno" n="urn:cts:froLit:geste.4006.geste_transcr_P4">

Moving all to `body/@n` solved the problem:

    <body n="urn:cts:froLit:geste.4006.geste_transcr_P4" xml:lang="xno">

It might be that HookTest does not look on <text> for @xml:lang, perhaps ?

**Comment by PonteIneptique** [comment]
Change s been proposed in #112
