### ISSUE TITLE
Deprecating the old hooktest parts

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/HookTest#117]
As HookTest became a wonderful Travis Compatible tool, some stuff feel like a burden to test or keep, and that has mostly to do with pulling from a repository. I am wondering if we should keep this on the next version (1.2.0) or simply deprecating it ?

**Comment by PonteIneptique** [comment]
Should remove : 

- [ ] Inline Printing
- [ ] Cloning

**Comment by sonofmun** [comment]
Cloning is only in the unit tests, right? Or am I misunderstanding what you mean by this?

**Comment by PonteIneptique** [comment]
Fixed. Cloning was also a function of the old hooktest :')
