### ISSUE TITLE
Make long description easier to read on pypi

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/HookTest#131]
Add

```python
    long_description_content_type="text/markdown",
```

to setup.py according to https://packaging.python.org/tutorials/packaging-projects/#setup-args

**Comment by sonofmun** [comment]
Does .rst (restructured text) fall under markdown? Or do we need a more precise designation?

**Comment by sonofmun** [comment]
Looks like we need "text/x-rst" instead. https://packaging.python.org/guides/distributing-packages-using-setuptools/#description

**Comment by PonteIneptique** [comment]
Most probably yes :D I forgot we had RST and not MD
