### ISSUE TITLE
HookTest fails to spot missing metadata file

### ISSUE THREAD

**Issue by Jean-Baptiste-Camps** [Capitains/HookTest#142]
I have encountered a weird behaviour: I have been able to validate with HookTest a data folder, where the root textgroup `__cts__.xml` file was missing (causing afterwards Nemo to parse nothing of the corpus).

Here is the log of the integration with Travis, showing now error:
https://travis-ci.com/Jean-Baptiste-Camps/geste-nemo/builds/107233541

While the metadata file was missing: https://github.com/Jean-Baptiste-Camps/geste-nemo/tree/a6687bb5c4d020e1cb471fcb5a519e9c1bd79630/data/geste

**Comment by PonteIneptique** [comment]
There is no errors in the link. Closing the issue.
