### ISSUE TITLE
First1KGreek Travis Build fails because of metadata

### ISSUE THREAD

**Issue by ThomasK81** [Capitains/HookTest#156]
Behaviour: Build fails: https://travis-ci.org/github/OpenGreekAndLatin/First1KGreek/builds/653634150

Details: The build is a rebuild of the successful: https://travis-ci.org/github/OpenGreekAndLatin/First1KGreek/builds/646593191

Expected behaviour: The build shouldn't fail.

**Comment by PonteIneptique** [comment]
This is related to a dependency of MyCapytain, hotfix has been pushed, waiting on Matt for this.

**Comment by PonteIneptique** [comment]
Should be fix now on Travis, no need to change anything.
Also, I would recommend using python 3.7 on your travis builds.

**Comment by ThomasK81** [comment]
Thanks for the quick bug fix. Rebuilding now for testing. I will let you know whether it has worked and then issue can probably be closed. Thanks again! :)

**Comment by ThomasK81** [comment]
Everything worked! Thanks again!
