### ISSUE TITLE
HookTest with Travis fails

### ISSUE THREAD

**Issue by pharos-alexandria** [Capitains/HookTest#157]
Cf. https://travis-ci.com/github/PatristicTextArchive/pta_data/builds/216419930

I use `-scheme auto` and it seems that the download of the rng fails:

```
Traceback (most recent call last):

  File "/opt/python/3.5.10/lib/python3.5/shutil.py", line 544, in move

    os.rename(src, real_dst)

FileNotFoundError: [Errno 2] No such file or directory: '.rngs/9e1230361d9ac3168e981da2c494470f.rng-indownload' -> '.rngs/9e1230361d9ac3168e981da2c494470f.rng'
```

Doing HookTest local it works without errors.

How can I solve this issue?

**Comment by PonteIneptique** [comment]
Can you try first simply updating python to 3.7 ?

**Comment by pharos-alexandria** [comment]
Worked, sorry for the bother.

**Comment by PonteIneptique** [comment]
Always a pleasure to help ^^

**Comment by pharos-alexandria** [comment]
Problem is there again with https://travis-ci.com/github/PatristicTextArchive/pta_data/builds/234874515 and python 3.7.1:

> FileNotFoundError: [Errno 2] No such file or directory: '.rngs/9e1230361d9ac3168e981da2c494470f.rng-indownload'

**Comment by PonteIneptique** [comment]
Hey :) I was on vacation. Is this solved ?

**Comment by pharos-alexandria** [comment]
Yes, it was there and gone again... So it is solved. Sorry for the bother.

**Comment by PonteIneptique** [comment]
I assume it might be due to download failing, I should definitely investigate this one day (soon ?)
