### ISSUE TITLE
more descriptive error for failing capitains guidelines

### ISSUE THREAD

**Issue by balmas** [Capitains/HookTest#20]
Currently says "Text can't be read through Capitains standards"

Would be good if it was more explicit about *which* standards failed (e.g. wrong filename, etc.)

**Comment by PonteIneptique** [comment]
This one is actually a tough one, but I conceed the issue.
Basically, this can be a lot of thing. What it means is that MyCapytain failed to ingest it...

**Comment by PonteIneptique** [comment]
I am actually removing this feature as we dropped the main part of this in the newer API of MyCapytain !
