### ISSUE TITLE
HookTest sends wrong status when some test fails

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/HookTest#25]
See http://ci.perseids.org/api/rest/v1.0/code/OpenGreekAndLatin/csel-dev/unit?uuid=f271cfe7-7458-48fe-bd43-a4dd4a179cf2&unit=OpenGreekAndLatin/csel-dev/data/stoa0162/stoa004/stoa0162.stoa004.opp-lat1.xml

- Happens with Duplicate Found

@sonofmun Could you join the json dumps of both your test ( master and without // tests ? ) locally so I can compare them ?

**Comment by sonofmun** [comment]
The test results.
[csel_master_hookresults.txt](https://github.com/Capitains/HookTest/files/57124/csel_master_hookresults.txt)

**Comment by sonofmun** [comment]
Here are the results for the edited xpaths.

[hookresults.txt](https://github.com/Capitains/HookTest/files/57142/hookresults.txt)
