### ISSUE TITLE
Adjust Hook test

### ISSUE THREAD

**Issue by annettegessner** [Capitains/HookTest#29]
Adjust hook test for the citation length difference

see https://github.com/PerseusDL/Nemo/issues/14 and 
https://github.com/OpenGreekAndLatin/csel-dev/issues/277

**Comment by PonteIneptique** [comment]
Hey Annette, thanks, I was kinda busy yesterday and forgot about it...

**Comment by annettegessner** [comment]
No problem, I just hope, you know what my rather short issue is about. ;-)

**Comment by PonteIneptique** [comment]
This was mostly an issue with eXist Implementation.
