### ISSUE TITLE
Provide information about the rng files version on executing HookTest, automatically update rng if necessary

### ISSUE THREAD

**Issue by nevenjovanovic** [Capitains/HookTest#54]
**Problem**: schema `.rng` files in `HookTest/resources` may become outdated, that is, the XML validation rules they represent may change in a later edition of the schema. Therefore, XML that validates elsewhere (e. g. in oXygen) may fail the HookTest validation.
**Proposed solutions**: there are two steps that could be taken. **First**, at the beginning of HookTest, provide information on version of `.rng` schema used, and an instruction on what to do if we're using a different schema version. **Second**, update `.rng` files as necessary; if possible, automatically.
**An issue with the second proposed solution**: it is not clear to me _when_ to perform the check whether .rng files have been updated. But, once this is decided, the `tei_all.rng` file could be pulled by a script from the [relevant URL of the TEI current edition](http://www.tei-c.org/Vault/P5/current/xml/tei/custom/schema/relaxng/). The current EpiDoc schema can be pulled from [www.stoa.org/epidoc/schema/latest/](http://www.stoa.org/epidoc/schema/latest/).

**Comment by PonteIneptique** [comment]
Connected to #58
