### ISSUE TITLE
recent change to Hook causing new test fails

### ISSUE THREAD

**Issue by lcerrato** [Capitains/HookTest#55]
things that passed on 12/21 are now failing.
Coverage in PerseusDL/canonical-greekLit went from 43% to 22%.

**Comment by balmas** [comment]
fyi, I've disabled repository updates in the cts.perseids.org environment until this is fixed, so that we don't lose a bunch of texts there in the middle of the SCS workshops we're running this week...

**Comment by PonteIneptique** [comment]
It is quite possible that locally these test passes : it seems HookTest runs on python2 on homer...

http://ci.perseids.org/api/rest/v1.0/code/PerseusDL/canonical-greekLit/unit?uuid=b32c48bf-a738-491a-bcdc-b3d9dd40db7d&unit=PerseusDL/canonical-greekLit/data/tlg0007/tlg002/tlg0007.tlg002.perseus-grc2.xml > UnicodeDecodeError is a python2 error

**Comment by PonteIneptique** [comment]
I can confirm there is an issue with the installation on homer. Just tested it on @1ec5948
