### ISSUE TITLE
Add a --travis output

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/HookTest#56]
CI output is designed to work with Travis, and as such : 

- [x] When an unit has only passing tests, change output to `\t/path/to/unit passes`
- [x] When an unit has no passing tests, change output to `\t/path/to/unit is failing all tests`
- [x] When an unit has some passing tests, change output to only focus on failed ones
```
\t/path/to/unit failed :
\t\tVerbose of first
\t\tVerbose of second
```
- [ ] If verbose, tests should display a second line : `\t\tX Level1Name, Y Level2Name, Z Level3Name`
- [x] Failing should exit 1 apparently (Need to check though)
- [ ] Automatically set 3 workers as well as target repo if possible ?

**Comment by PonteIneptique** [comment]
A unit here is a file : a text or a `__cts__.xml` file

**Comment by PonteIneptique** [comment]
```python

        if self.travis is True:
            if isinstance(log, UnitLog):
                if log.status is True:
                    print("\t{path} passes".format(path=log.name))
                    if self.verbose:
                        # do something with verbose.
                    print(verbose stuff)
                else:
                    do something else
```

**Comment by PonteIneptique** [comment]
![dgmmofbkegibochf](https://cloud.githubusercontent.com/assets/1929830/22772819/295fdec2-ee9f-11e6-80f3-78178edef728.png)
> 1) This output will be well over 1000 lines for canonical-latinLit because every file that only fails some of the tests will have several lines of output.
> 2) I am not yet sure the best way to put in the extra information about the tests if the user chooses --verbose. We can discuss this at some future time.
Anyway, let me know what you think (when you have time and energy). I am stopping for the evening.

From Matt

**Comment by PonteIneptique** [comment]
Few thoughts before talking, if we talk this morning : 

- Remove one tab
- Do not show `__cts__.xml` passing. We might want to simply display (except for failing ones) in between process : `X/Z __cts__.xml passing` and then display verbosity.
- Verbosity might be dealt with at the end, by looping over the results that are True and:
  - only using the filename for texts (not full path) with following statement : `phi1294.phi002.perseus-lat2: 14\t1500\t14000` or some pretty table ( https://pypi.python.org/pypi/PrettyTable ). This is most likely something to store
  - the same table could show word count as first data column
  - For `__cts__.xml` we might only display the URN that were found in an ordered list ? Not even sure this makes sense but just in case ?

Another way to work this out that takes back on what I just wrote : 

- Deal with `__cts__` first
   - Only write one dot per passing unit and one X per failing one.
   - Then display failed tests in a pretty table, one column for labels, one for error messages
   - Write a pretty table with textgroup, work and edition/translation URNs ( show language as well )
- Deal with text units
   - Only write one dot per passing unit and one X per failing one.
   - Then display failed tests in a pretty table, one column for labels, one for error messages
   - Display passage and word counts in pretty table

Another way : 
- Keep the idea of pretty table for part of verbosity (the success part)
- Add color for passing and failing (purple/red [purple better for color blind people])
- Failing test should be joined `"Failing : " + ", ".join(logs)`  or something like this

**Comment by PonteIneptique** [comment]
Addendum : the limit is 10k lines, not one k. Though I still think reducing the number of lines is hugely important.

**Comment by PonteIneptique** [comment]
3 columns for texts : 

| Identifier | Words | Nodes |
|------------|----------|----------|
| urn:cts:latinLit... | 25000 | 14,1500,24000 |

**Comment by PonteIneptique** [comment]
```python
    def passages(self):
        """  Check that passages are available at each level. On top of that, it checks for forbidden characters \
        and duplicate in references

        """
        if self.Text and self.Text.citation.refsDecl:
            citations = [c.name for c in self.Text.citation]
            for i in range(0, len(self.Text.citation)):
                try:
                    with warnings.catch_warnings(record=True) as warning_record:
                        # Cause all warnings to always be triggered.
                        warnings.simplefilter("always")
                        passages = self.Text.getValidReff(level=i+1, _debug=True)
                        ids = [ref.split(".", i)[-1] for ref in passages]
                        space_in_passage = TESTUnit.FORBIDDEN_CHAR.search("".join(ids))
                        len_passage = len(passages)
                        status = len_passage > 0 and len(warning_record) == 0 and space_in_passage is None
                        self.log(str(len_passage) + " found")
                        self.citation.append((i, len_passage, citations[i]))
                        for record in warning_record:
                            if record.category == DuplicateReference:
                                passages = sorted(str(record.message).split(", "))
                                self.log("Duplicate references found : {0}".format(", ".join(passages)))
                        if space_in_passage and space_in_passage is not None:
                            self.log("Reference with forbidden characters found: {}".format(
                                " ".join([
                                    "'{}'".format(n)
                                    for ref, n in zip(ids, passages)
                                    if TESTUnit.FORBIDDEN_CHAR.search(ref)
                                ])
                            ))

                        yield status
                except Exception as E:
                    self.error(E)
                    self.log("Error when searching passages at level {0}".format(i+1))
                    yield False
        else:
            yield False
```

**Comment by sonofmun** [comment]
Extreme non-verbosity. Could be useful, though I am not sure:

![image](https://cloud.githubusercontent.com/assets/3787067/22778731/476d20aa-eeb8-11e6-8f24-7e13381203bc.png)

**Comment by PonteIneptique** [comment]
You could keep this as an option actually. Like --light-output or so. Moreover if we are able to upload some more data to another service. Or if people do not care :)

**Comment by PonteIneptique** [comment]
I still think though that you should split cts and text units ;)

**Comment by sonofmun** [comment]
First results with a table:

![image](https://cloud.githubusercontent.com/assets/3787067/22782893/7cfb5d02-eec9-11e6-809e-2da7ee3fcfe3.png)

**Comment by PonteIneptique** [comment]
Looks great!

Le 9 févr. 2017 1:13 PM, "Matthew Munson" <notifications@github.com> a
écrit :

**Comment by sonofmun** [comment]
We just need to filter out the test results that we don't want.
And we also need to figure out how to print results for the Unique Nodes test when there are duplicate nodes.

**Comment by sonofmun** [comment]
Also, is there some reason not to use the same output when printing to console?

**Comment by sonofmun** [comment]
Oh, and printing output in color. Perhaps https://pypi.python.org/pypi/termcolor

**Comment by PonteIneptique** [comment]
Maybe we should call --travis simplifiedconsole

Le 9 févr. 2017 2:19 PM, "Matthew Munson" <notifications@github.com> a
écrit :

**Comment by sonofmun** [comment]
I think that is a good idea. I will go ahead and change it. Or I could change --console to take an argument, e.g., "normal" or "simplified". Though that might entail too much change in the code.

**Comment by PonteIneptique** [comment]
or have --format or something. We can think about it more when it is done :)

**Comment by sonofmun** [comment]
The problem with --format would be that someone might want JSON and/or HTML, and printing to the console. So I think just having different formats for printing to the console seems to be a better idea to me.

**Comment by PonteIneptique** [comment]
That makes sense.
Let's just wait for the thing to be finished and decide there :)

**Comment by sonofmun** [comment]
So, next question: what should be shown when --verbose==True and what should be shown when --verbose==False

**Comment by PonteIneptique** [comment]
maybe --verbose_level [1,2,3] ?

**Comment by PonteIneptique** [comment]
Oh. Actually, what we were doing before in non verbose : do not show duplicate, forbiden, words, nodes numbers

**Comment by PonteIneptique** [comment]
In regards to https://github.com/Capitains/Hook/issues/61 , it would be great to have at the end an output such as

```bash
>>> Failed [6 over9] etc...
HookTestResults: texts=500 texts_passing=355 metadata=200 metadata_passing=155 coverage_units=78.5 total_nodes=78645 words=500
```

Where 
- texts and texts_passing represents data about texts
- metadata and metadata_passing represents data about `__cts__`
- coverage_units is the percentage of tests that run well
- total_nodes is the sum of nodes found at every level (So if one text has 5, 10, 20 it adds 35 nodes)
- words is the total number of words

**Comment by sonofmun** [comment]
I think all the items on the checklist have been completed. Check the output (e.g., https://travis-ci.org/sonofmun/canonical-lat-test) to make sure it looks like you want it to. And the workers and target repo are set in the .travis.yml file.

**Comment by PonteIneptique** [comment]
Did you switch the previous system ? for this one ?

**Comment by sonofmun** [comment]
The current one is the only --travis option right now. It needs some tweeks but I think those should probably come in their own issues.
