### ISSUE TITLE
Wordcount should be language based

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/HookTest#68]
WordCount should be based on the language the text is in, using metadata from `__cts__.xml` :)

**Comment by sonofmun** [comment]
Why not use the xml:lang attribute from the XML text file instead of from the metadata file?

**Comment by PonteIneptique** [comment]
@sonofmun Follow what we talked about during the call this morning :)

**Comment by sonofmun** [comment]
That's what I thought. I have it on issue #70
