### ISSUE TITLE
Test for xml:lang attribute

### ISSUE THREAD

**Issue by sonofmun** [Capitains/HookTest#70]
On /TEI/text/body in TEI
On /TEI/text/body/div[@type="edition" OR @type="translation"] in epiDoc.

**Comment by PonteIneptique** [comment]
Dont forget type translation

**Comment by sonofmun** [comment]
Corrected.

**Comment by sonofmun** [comment]
I also added this in PR #65

**Comment by PonteIneptique** [comment]
Can you make a PR to update the CHANGES.txt then ?

**Comment by sonofmun** [comment]
Done
