### ISSUE TITLE
Add commentary parsing to CTS Inventory Unit

### ISSUE THREAD

**Issue by PonteIneptique** [Capitains/HookTest#89]
- [x] https://github.com/Capitains/HookTest/blob/master/HookTest/capitains_units/cts.py#L110-L113
- [x] https://github.com/Capitains/HookTest/blob/master/HookTest/capitains_units/cts.py#L190
- [x] https://github.com/Capitains/HookTest/blob/master/HookTest/capitains_units/cts.py#L215
- [x] Changes.txt
- [x] Setup.py
- [x] Tests (including a test run ?)

**Comment by sonofmun** [comment]
@PonteIneptique I assume this issue can be close.
