### ISSUE TITLE
Check Duplicate Nodes 

### ISSUE THREAD

**Issue by sonofmun** [Capitains/HookTest#92]
Make sure the failed test shows up on the list of failed tests above as well as the list of duplicate nodes below.

**Comment by sonofmun** [comment]
I have no idea what this refers to. As far as I know, whenever there are duplicate nodes, it shows up both in the table and in the list of dupes below the table. So I think this can be closed.

**Comment by PonteIneptique** [comment]
![](https://media.giphy.com/media/8UF0EXzsc0Ckg/giphy.gif)
