### ISSUE TITLE
Add display of DTD errors

### ISSUE THREAD

**Issue by sonofmun** [Capitains/HookTest#95]
At this point, the table display on Travis does not display the type of epiDoc DTD errors. Sometimes these errors do not show up in Oxygen, for whatever reason. 
Solution: implement the DTD error information that is shown in the inline output at the bottom of the tests, as with duplicate nodes.

**Comment by PonteIneptique** [comment]
@sonofmun It can be a version difference, which makes my comment about rng even more pressing ;)

**Comment by PonteIneptique** [comment]
I think you'd better allow to use a specific version of a DTD / ODD but more likely a RNG using jing :)

**Comment by sonofmun** [comment]
Version of the DTD, you mean? The error that was showing up in this case was that epiDoc does not allow the source attribute on an `<lb>` element, while TEI does. For some reason (the `@xmlns` on the teiHeader?), Oxygen did not show this as an error while HookTest did.
That is not to say that the RNG thing is not important. Just to talk about this specific case. And to consider more explicit error messages where they are appropriate, which I think is a good idea.

**Comment by PonteIneptique** [comment]
It can definitely be the xmlns. Though we discussed also a while back that showing xmlns error would be too heavy for Travis (size of reply) and as such reinstating it would be bad. 

People also need to be careful locally and a text that has no epidoc loaded at the top should not even go to tests...

**Comment by sonofmun** [comment]
That is the weird thing. It has the epidoc declaration at the top. Here is the file: https://github.com/ahanhardt/First1KGreek/blob/issue-142/data/tlg2034/tlg007/tlg2034.tlg007.opp-grc1.xml I would be interested to know if your version of Oxygen displays the error.

**Comment by PonteIneptique** [comment]
I stand on my comment : it is possible the latest epidoc allowed that. I just tested it with the latest one ;)

**Comment by PonteIneptique** [comment]
Which means we needs to allow specification (specify a single validation scheme / do an auto valid using xml-model infos.

**Comment by sonofmun** [comment]
I am fine with implementing the specification. 
But how did you test with the latest .rng? I copied the text from http://www.stoa.org/epidoc/schema/latest/tei-epidoc.rng into the epidoc.rng file that we have locally in HookTest, ran the test with hooktest on this repo, and it still fails with the same error. And if you look at the definition for `<lb>` in the .rng under that link, it does not include att.global.source as possible attributes. So, if I am reading that correctly, `@source` is still an illegal attribute on `<lb>`. Or am I looking in the wrong place or misunderstanding something?

**Comment by PonteIneptique** [comment]
That feels weird because it did not fail for me in Oxygen, even specifying the RNG manually...

**Comment by PonteIneptique** [comment]
If I had to do auto-rng-download depending on xml declaration :
1. Read the RNG that is/are declared (I think there can be multiple one \o/ )
2.Check If the RNG
  - is local : set it up for the next tests if 
  - is remote :
    1. Compute SHA of the address of the document (or MD5, a simple hash of the URI)
    2. Check if ./cache-download/Sha(URI) exists
       - If not download it
    3. Set it up for the test
3. Run Jing

**Comment by sonofmun** [comment]
This issue has been resolved in PR #107
